### ISSUE TITLE
[Feat] 코드 컨벤션 적용

### ISSUE THREAD

**Issue by luke0408** [Say-Better/Service-Server#1]
## Describtion
> [NEVER CAMPUS HACKDAY의 Java Code Conventions](https://naver.github.io/hackday-conventions-java/) 기반 코드 컨벤션 적용하기

## To-DO
> 작업 계획 작성
- [x] coding convention 적용
  - [x] .editorconfig 코드 컨벤션 적용
  - [x] Intellij 코드 컨션 적용
- [ ] coding convention 문서 작성
  - [ ] java 컨벤션 관련 :  checkstyle로 확인할 수 없는 규칙 위주
    - 명명 규칙
    - 테스트 규칙
  - [ ] 패키지 구조 관련
  - [ ] URI Design, HTTP Method 관련
  - [ ] Response 응답 코드 관련
  - [ ] Resourece 별 Response 응답 메세지 관련

## Reference

- [NEVER CAMPUS HACKDAY의 Java Code Conventions](https://naver.github.io/hackday-conventions-java/)
- [파트너플랫폼 스쿼드 코드 컨벤션](https://oliveyoung.tech/blog/2023-12-05/partner-platform-code-convention/)
- [[우아한테크코스/프리코스] Java Code Conventions를 IntellJ에 적용하기](https://programmer-ririhan.tistory.com/338)
- [Spring Guide - Directory](https://cheese10yun.github.io/spring-guide-directory/)
- [Spring Guide - Exception 전략](https://cheese10yun.github.io/spring-guide-exception/)
