### ISSUE TITLE
[Feat] spring security 적용 및 cors 문제 해결

### ISSUE THREAD

**Issue by luke0408** [Say-Better/Service-Server#10]
## Describtion
> spring security 적용 및 cors 문제 대응

## To-DO
> 작업 계획 작성
- [x] spring security 적용
- [x] swagger 설정 적용
- [x] cors 문제 대응
- [x] test api 동작 테스트

## Reference
- [Spring Boot 3.x + Security 6.x 기본 설정 및 변화](https://velog.io/@kide77/Spring-Boot-3.x-Security-%EA%B8%B0%EB%B3%B8-%EC%84%A4%EC%A0%95-%EB%B0%8F-%EB%B3%80%ED%99%94)
- [[SpringBoot] Spring Security 처리 과정 및 구현 예제](https://mangkyu.tistory.com/77)

**Comment by luke0408** [comment]
## Spring Security 설정 관련 레퍼런스

- https://github.com/keede7/boot-latest-starter/blob/security/src/main/java/io/keede/bootlateststarter/security/config/SecurityConfig.java
- https://velog.io/@pizza_1/Spring-Security-6-%ED%8A%9C%ED%86%A0%EB%A6%AC%EC%96%BC-5

## Cors 설정 관련 레퍼런스

- https://docs.spring.io/spring-security/reference/servlet/integrations/cors.html
- https://github.com/BETTER-iTER/Server/blob/main/src/main/java/com/example/betteriter/global/config/web/CorsConfig.java
