### ISSUE TITLE
[Feature] 초기정보 입력 API

### ISSUE THREAD

**Issue by destiny3912** [Say-Better/Service-Server#112]
## Type of change

- [X] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [ ] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**

초기 정보 입력 API를 구현한다.
입력 정보
- 프로필 사진
- 유저 이름

## **Todo**

- [ ] API 구현
- [ ] 테스트코드 작성
