### ISSUE TITLE
[Feature] 학습자 등록 코드 관련 API

### ISSUE THREAD

**Issue by destiny3912** [Say-Better/Service-Server#117]
## Type of change

- [X] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [ ] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**

학습자 등록 코드 관련한 API를 작성한다
등록 코드는 영문 대문자와 숫자를 섞은 6자리의 코드로 한다.

## **Todo**

- [ ] 학습자 등록 코드 발급 API
- [ ] 학습자 등록 코드 검증 API
