### ISSUE TITLE
[Refactor] Mysql DB 연결 설정 수정

### ISSUE THREAD

**Issue by luke0408** [Say-Better/Service-Server#123]
## Type of change

- [ ] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [x] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**

아래의 두가지 이유로 인해 DB 커넥션 설정을 수정 하기로 하였습니다.
- DB connection 설정이 제대로 적용되지 않는 상황 발생
- 이후 Test 컨테이너 적용을 위해 기존 방법 수정

## **Todo**

- [ ] Mysql DB 연결 설정 수정
