### ISSUE TITLE
[Feature] Redis 환경 설정 수정

### ISSUE THREAD

**Issue by luke0408** [Say-Better/Service-Server#127]
## Type of change

- [x] Feature : 새로운 기능 추가
- [x] Bug fix : 버그 수정
- [x] Refactor : 코드 리팩토링 작업

## **Description**

Redis 환경 수정하기

## **Todo**

- [ ] 환경 수정
