### ISSUE TITLE
[Feat] CI/CD 구축

### ISSUE THREAD

**Issue by luke0408** [Say-Better/Service-Server#14]
## Describtion
> GCP + github action + docker 기반 CI/CD 환경 구축

## To-DO
> 작업 계획 작성
- [x] remote 및 local 환경 yml 파일 수정
- [x] docker file 작성
- [ ] github workflow 작성
  - [ ] CI 구축
  - [ ] CD 구축
