### ISSUE TITLE
[Feat] 솔루션 제작 기능 구현

### ISSUE THREAD

**Issue by luke0408** [Say-Better/Service-Server#24]
## Describtion
> 학습을 위한 솔루션 제작 기능 구현

## To-Do
> 작업 계획 작성
- [x] symbol 추천 기능 구현
- [x] symbol 검색 기능 구현
- [x] 솔루션 제작 기능 구현
