### ISSUE TITLE
[Chore/Style] 코드 포멧 변경 및 자동화 workflow 적용

### ISSUE THREAD

**Issue by luke0408** [Say-Better/Service-Server#28]
## Type of change

- [x] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [x] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [x] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [x] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**

- code format을 적용한다
- 다양한 자동화 workflow를 적용한다

## **Todo**

- [x] code format 적용
  - [x] checkstyle
  - [x] sonarLint
- [x] 자동화 workflows
  - [x] 라벨링 자동화
  - [x] 작업자 등록 자동화
  - [x] lint 검사 자동화
