### ISSUE TITLE
[Refactor] 멀티 모듈 변경

### ISSUE THREAD

**Issue by luke0408** [Say-Better/Service-Server#30]
## Type of change

- [ ] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [x] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**

싱글 모듈로 구성된 현재의 프로젝트를 분리한다

## **Todo**

- [ ] 모듈 분리
  - [ ] Core 모듈
  - [ ] Client 모듈
  - [ ] Storage 모듈
  - [ ] Support 모듈
  - [ ] Test 모듈
- [ ] 빌드 테스트

## **Reference(Optional)**

- [스프링 부트 단일 모듈 코드에 멀티 모듈을 적용하여 프로젝트 구조 개선하기](https://velog.io/@jonghyun3668/%EC%8A%A4%ED%94%84%EB%A7%81-%EB%B6%80%ED%8A%B8-%EB%8B%A8%EC%9D%BC-%EB%AA%A8%EB%93%88-%EC%BD%94%EB%93%9C%EC%97%90-%EB%A9%80%ED%8B%B0-%EB%AA%A8%EB%93%88%EC%9D%84-%EC%A0%81%EC%9A%A9%ED%95%98%EC%97%AC-%ED%94%84%EB%A1%9C%EC%A0%9D%ED%8A%B8-%EA%B5%AC%EC%A1%B0-%EA%B0%9C%EC%84%A0%ED%95%98%EA%B8%B0)
- https://github.com/team-dodn/spring-boot-java-template

**Comment by luke0408** [comment]
# Gradle Plugin java vs java-library

> 참고자료
> - [[Gradle] Gradle Java 플러그인과 implementation와 api의 차이](https://mangkyu.tistory.com/296)
