### ISSUE TITLE
[Docs] 멀티파트 코드 기반으로 README 수정

### ISSUE THREAD

**Issue by luke0408** [Say-Better/Service-Server#32]
## Type of change

- [ ] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [ ] Refactor : 코드 리팩토링 작업
- [x] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**

멀티 파트로 수정된 코드를 기반으로 README 파일 수정 진행

## **Todo**

- [ ] README 수정
- [ ] 파일 트리 설명 수정
