### ISSUE TITLE
[Refactor] core 모듈 코틀린 리펙터링

### ISSUE THREAD

**Issue by luke0408** [Say-Better/Service-Server#33]
## Type of change

- [ ] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [x] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [x] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**

코어 모듈 코드를 코틀린 기반으로 리펙토링 한다

## **Todo**

- [x] core 모듈 리펙터링
  - [x] core-api 모듈
  - [x] core-enum 모듈
- [x] 빌드 테스트 

## **Reference(Optional)**

- [우당탕탕 Kotlin 전환기](https://dealicious-inc.github.io/2022/08/29/kotlin-converting.html)
- [Spring Boot & JPA에서 Java와 Kotlin을 함께 사용하기](https://tech.inflab.com/20240110-java-and-kotlin/)

**Comment by luke0408** [comment]
# JVM Signature Error

https://velog.io/@_im_ssu/JVM-signature-error-%EB%8C%80%EC%B2%98%ED%95%98%EA%B8%B0

# Kotlin aop

https://tech.kakaopay.com/post/overcome-spring-aop-with-kotlin/#%ED%81%B4%EB%9E%98%EC%8A%A4-%EB%82%B4%EB%B6%80-%ED%95%A8%EC%88%98-%ED%98%B8%EC%B6%9C-by-kotlinaop

https://velog.io/@slolee/Kotlin-Trailing-Lambda-%EB%A5%BC-%EC%9D%B4%EC%9A%A9%ED%95%B4-Spring-AOP-%EB%82%B4%EB%B6%80%ED%98%B8%EC%B6%9C%EB%AC%B8%EC%A0%9C-%EA%B7%B9%EB%B3%B5%ED%95%98%EA%B8%B0
