### ISSUE TITLE
[Refactor] clients 모듈 kotlin으로 변경

### ISSUE THREAD

**Issue by luke0408** [Say-Better/Service-Server#36]
## Type of change

- [ ] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [x] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [x] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**

- clients 모듈을 kotlin으로 변경 한다.

## **Todo**

- [x] clients 모듈 변경
  - [x] clients:client-symbol
- [x] build test
