### ISSUE TITLE
[CI/CD] 개발 서버 배포용 도커 컴포즈 파일 생성

### ISSUE THREAD

**Issue by luke0408** [Say-Better/Service-Server#38]
## Type of change

- [x] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [ ] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [x] CI/CD : CI/CD 작업 수정
- [x] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**

Nginx, Redis, Spring Boot 를 각각 docker 컨테이너로 사용하는 도커 컴포즈 파일 구현

## **Todo**

- [ ] docker-compose file 생성
- [ ] docker-compose file test

## **Reference(Optional)**

- Nginx 쿡북
- [docker-compose를 이용하여 로컬 개발환경 구성하기(Part1)](https://dev.gmarket.com/72)
