### ISSUE TITLE
[Feature] 구글 소셜 로그인 에러 해결

### ISSUE THREAD

**Issue by luke0408** [Say-Better/Service-Server#39]
## Type of change

- [ ] Feature : 새로운 기능 추가
- [x] Bug fix : 버그 수정
- [ ] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**

구글 소셜 로그인에 대한 리다이렉션 요청은 들어가는데 정보 반환이 안되는 문제 발생

## **Todo**

- [ ] 문제 원인 확인
- [ ] 문제 해결
