### ISSUE TITLE
[CI/CD] gitHub Actions Jenkins 트리거 설정

### ISSUE THREAD

**Issue by destiny3912** [Say-Better/Service-Server#41]
## Type of change

- [X] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [ ] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**

기존 gitHubActions CI-CD 파일에 GCP 배포 관련 설정 제거 및 Jenkins 트리거 작성

## **Todo**

- [ ] GCP 배포 관련 설정 제거
- [ ] Jenkins 트리거 작성

**Comment by destiny3912** [comment]
AWS로의 인프라 전환으로인한 closed
