### ISSUE TITLE
[Test] 컨트롤러 단위 테스트 작성 및 테스트 최적화 목적 리팩토링

### ISSUE THREAD

**Issue by asas6978** [Say-Better/Service-Server#42]
## Type of change

- [ ] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [x] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [x] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [x] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**

- 컨트롤러 단위 테스트 작성
- 테스트 정상 동작을 위해 Feature 단계에서 코드 작성 시 생략했던 옵션 추가
- 테스트에 이용되는 외부 라이브러리 추가

## **Todo**

- [ ] AuthControllerTest 작성 완료
- [ ] MemberControllerTest 작성 완료
- [ ] ReviewControllerTest 작성 완료
- [ ] SolutionControllerTest 작성 완료
