### ISSUE TITLE
[Chore/Test] 테스트 코드 패키지 이동 및 코드 보완

### ISSUE THREAD

**Issue by asas6978** [Say-Better/Service-Server#45]
## Type of change

- [ ] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [ ] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [x] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [x] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**
- tests 모듈 내 테스트 코드 패키지 이동
- build.gradle 내 불필요한 dependency 제거
- 테스트 메서드 설명 추가

## **Todo**

- [x] 테스트 코드 위치를 main에서 test로 옮기기
- [x] build.gradle 수정
- [x] 테스트 메서드에 DisplayName 어노테이션 추가
