### ISSUE TITLE
[CI/CD] AWS Elastic Beanstalk 기반 cicd 환경 구축

### ISSUE THREAD

**Issue by luke0408** [Say-Better/Service-Server#47]
## Type of change

- [x] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [ ] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [x] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**

AWS 서버 cicd 배포 환경 구축

## **Todo**

- [ ] 서버 헬스 체크용 api 개발
- [ ] AWS 엘라스틱 빈스톡 환경 구축
- [ ] CICD github action 구축

**Comment by luke0408** [comment]
gradle build issue 로 인해 docker-compose 환경을 구축하는 것으로 마무리
