### ISSUE TITLE
[Feat] RabbitMQ 모듈 및 DB 엔티티 일부 수정

### ISSUE THREAD

**Issue by destiny3912** [Say-Better/Service-Server#48]
## Type of change

- [X] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [ ] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**

솔루션 진행에 필요한 API들을 작성 및 그에 따라 필요한 모듈의 제작

## **Todo**

- [ ] RabbitMQ 인터페이스
- [ ] DB 엔티티 일부 수정
