### ISSUE TITLE
[Feature] Member 엔티티 분리

### ISSUE THREAD

**Issue by asas6978** [Say-Better/Service-Server#49]
## Type of change

- [x] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [ ] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**

- Member 엔티티를 Educator, Learner 엔티티로 분리

## **Todo**

- [ ] 엔티티 분리
