### ISSUE TITLE
[Feature] 솔루션 진행 프로세스

### ISSUE THREAD

**Issue by destiny3912** [Say-Better/Service-Server#53]
## Type of change

- [X] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [ ] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**

솔루션 진행 (시작과 종료)시 필요한 API의 구현

## **Todo**

- [ ] 솔루션 시작 API
- [ ] 솔루션 종료 API
