### ISSUE TITLE
[Refactor] gradle.kts 기반 multi module 환경 구축

### ISSUE THREAD

**Issue by luke0408** [Say-Better/Service-Server#56]
## Type of change

- [ ] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [x] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [x] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [x] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**

- 단순 gradle 기반의 multi module에서 gradlew.kts 기반의 moulti moudule 환경으로 변경
- java 기반으로 작성 되어있던 storage module을 kotlin으로 수정

## **Todo**

- [x] #58
- [x] #59
- [x] #60
- [x] #61
- [x] #62
- [x] #63
