### ISSUE TITLE
[Feature] lint 적용을 위한 git-hook 설정

### ISSUE THREAD

**Issue by luke0408** [Say-Better/Service-Server#71]
## Type of change

- [x] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [ ] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [x] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**

- code lint 적용을 위한 git-hook 설정 추가
- 기존에 적용되어있던 java lint 설정 제거

## **Todo**

- [ ] java lint 제거
- [ ] git-hook 설정 추가
