### ISSUE TITLE
[CI/CD] SSM 기반 cicd 파이프라인 작성

### ISSUE THREAD

**Issue by luke0408** [Say-Better/Service-Server#74]
## Type of change

- [x] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [ ] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [x] CI/CD : CI/CD 작업 수정
- [x] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**

SSM을 사용한 cicd 파이프라인 구축

## **Todo**

- [ ] SSM github action 작성
- [ ] cicd test 진행
