### ISSUE TITLE
[Style] ktlint 기반 코드 컨벤션 작업

### ISSUE THREAD

**Issue by luke0408** [Say-Better/Service-Server#75]
## Type of change

- [ ] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [ ] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [x] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**

kotlin 코드 컨벤션 lint 작성 및 formater 설정

## **Todo**

- [x] ktlint 설정
- [x] 코드 포멧팅
