### ISSUE TITLE
[Feature] Symbol 추천 API

### ISSUE THREAD

**Issue by asas6978** [Say-Better/Service-Server#82]
## Type of change

- [x] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [ ] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [x] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**

Symbol 추천 API 구현

## **Todo**

- [ ] Symbol 추천 API 구현
- [ ] 테스트 작성

**Comment by asas6978** [comment]
브랜치 재 생성으로 인한 커밋 기록 정리 차원에서 해당 이슈를 close 합니다.
