### ISSUE TITLE
[Refactor] 유저 소셜 로그인 로직 수정

### ISSUE THREAD

**Issue by luke0408** [Say-Better/Service-Server#86]
## Type of change

- [x] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [x] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**

- Member를 통해 교육자와 학습자를 발급해 사용하는 형태로 수정
- 소셜 로그인 로직 수정

## **Todo**

- [x] 교육자, 학습자 Entity 수정
- [ ] #89
- [x] 소셜 로그인 로직 수정

**Comment by luke0408** [comment]
- 변경 후 전체 도메인 구조
<img width="1833" alt="image" src="https://github.com/Say-Better/Service-Server/assets/98688494/d652c0a3-cb1f-47a3-b0f7-c1c05d47c190">


- 변경 후 전체 도메인 흐름 
<img width="1577" alt="image" src="https://github.com/Say-Better/Service-Server/assets/98688494/c1f55a28-e356-4afa-92ff-462887c2345e">
