### ISSUE TITLE
[Feature] 리뷰 API

### ISSUE THREAD

**Issue by destiny3912** [Say-Better/Service-Server#87]
## Type of change

- [X] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [ ] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**

솔루션 리뷰에 필요한 API를 작성한다.

## **Todo**

- [ ] 리뷰 진행 데이터 조회 API (리뷰 시작)
- [ ] 리뷰 완료 데이터 반영 API (리뷰 종료)

**Comment by destiny3912** [comment]
#150 에서 진행
