### ISSUE TITLE
[Refactor] core-enum 모듈 core-common으로 변경

### ISSUE THREAD

**Issue by luke0408** [Say-Better/Service-Server#97]
## Type of change

- [ ] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [x] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**

- #88 해당 pr 나눴던 대화를 기반으로 core-enum 모듈을 core-common으로 변경하고 몇가지 책임을 추가로 할당

[ 기존 ]
- 외부 의존성을 가지지 않는다.
- 프로젝트 전역에서 사용 가능한 `유틸리티성 클래스`를 작성한다. 
- 프로젝트 전역에서 사용 가능한 `데이터 타입 클래스`를 작성한다.
- 가능하면 수정하지 않으며 수정하게 되면 상의 후 수정을 진행한다.

[ 변경 및 추가 ]
- 필요에 따라 의존성을 가질 수 있다.
- 프로젝트 전역에서 사용 가능한 `유틸리티성 클래스`를 작성한다. 
- 프로젝트 전역에서 사용 가능한 `데이터 타입 클래스`를 작성한다.
- 자유롭게 수정은 가능하나 `새로운 개념의 추가`에 대해서는 상의 후 진행한다.

## **Todo**

- [x] core-common으로 변경
- [x] 전역 Exception 관리 책임 할당
- [x] 전역 ErrorCode 관리 책임 할당
